"""initial schema

Revision ID: c27f958dcda9
Revises: 
Create Date: 2026-07-18 17:14:55.650249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c27f958dcda9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Trip',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('usr_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('num_day', sa.Integer(), sa.Computed('end_date - start_date', ), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('trip_id')
    )
    op.create_index(op.f('ix_Trip_trip_id'), 'Trip', ['trip_id'], unique=False)
    op.create_table('User',
    sa.Column('usr_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('usr_id')
    )
    op.create_index(op.f('ix_User_usr_id'), 'User', ['usr_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_usr_id'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Trip_trip_id'), table_name='Trip')
    op.drop_table('Trip')
    # ### end Alembic commands ###
